language: java
jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "ferzerkerx-github"
    token:
      secure: "uI43alWp1l4Fe4WjKyiQwzkLQlUO2Fn4DK+dKbwbTOGjM4bzkoHNQ9R6xo82QNfN7n4MnPlK6A6MCDRtjF7De4qyo554xYMEb2Lned8MH75z1OpPBCnNyiGZIDRYrZR+lEN7WNckLWsKVqjxMPTagWEJN7UKdD+bYM7b92kx9+Xj5fxJ9DLDnbCsXbOG35d+xlRZkDXX9izPOa6LNPXLtE6YhwvSkGfUJ461OFhoStn9Q7N3Dw4/PRecYaK0KbMh9VmInoHHNZSM4iWQ7Mzj0Tk0b8YaA9ism7FucDQbMNXaoyl/XA6t46rRYQ/evZW71AyQ0t499Qqr2QK6dYTuB+Je6Bxw6k7dFfTulbxb9TA+2Ho9a/kM5q0HoJahNdwLB6OkQA9v+WrNh08GL8ZamAXxzkzY7KaQCex2XCB/ADPP8MXpKzLgWDEAW2ihXsnSE443YP1b12vdTmByWkhjdoo6tTJJYU3KGP2RarZRROso9IoGs2I7wtqn/k8yMMdpI8nNqWOJHt0g6eVKxgOD+yK4JdurCFd4Up/V7oGYDIgT8R+m15ETvo1yqFiEsvAHpAxGWI1r15HlRj78z5Hj3aCF97dtIS2pj2m87hgJ8HPVCNk6H7yj4fVs18BoYdSnT2IjGrPYZmbQwKqWjbLXveNzMdvjglZUKZEjw0oaZgQ="

env:
  secure: "RG30Y9evU9qp7XCxbnick5CcbzZI3RPzF00ZkrZsnYGvjDykM09N8GG17+PYdd9rCdsA48IQhW16wR4cHHBvMoqvTKtIcz9HUx5jfo+ij4cBunoH/Ptok/TkB812yQd30d3CuwjC9SyEo1BKAMeC9d/f2NCzHD7UNmUPshJAOn/5vBC+6hXUG2OXkCXWc9PQ+TAA1l3CtMJU2XAHXo8nFrnGZ9Pt5F4UoL2l4dmiRwgzo5Y0TKCPvOYjjip3LIc+l/QA/CE9+IWlwxSAgfJbiEmGUszLW7V5Lb4GtAogSkgw/uPPbRB1jYrz2Tiwajpypli7LmC9YR6OQQCN3YVjXuUUYtQUDkY6lMyhCYnodpUPT4SMQsqBPxjeojBmZv4BerG+k8R8CyLFfbZ8+h5Be6ZK0YvxOsoETnrkdA9hjgfua4yIcvwYtqvDlA41Kcvl3/PEogCk6pqvtLfCigJzwqJ8CFcoP0QufJTBeiTDF0I7YdVe8+Vn0DNh8T/Nitc1R9oQWKoMz8xUB7C2EtXvKw6gTw7zeHriaqd3K6eGrSobM8vZpZiyGnZ+wmUWYky6IAUNQ95MwvL3mxBHuVlLWgVmiB+FTGRi2F08STueK89d3Pv43VVfY9yQ4CXetWOvA2QMnOwpR2cnNZfKUzkqPGp4k7pAW3zo1alBwfoGBUw="

install:
  - "mvn clean compile"
  - "npm install -g snyk"

script:
  - "mvn -Dmaven.test.failure.ignore=false org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar"
  - "snyk test"

after_success:
  - snyk monitor