/*
 * This file is generated by jOOQ.
 */
package com.ferzerkerx.demo.joooq.db.tables;


import com.ferzerkerx.demo.joooq.db.Indexes;
import com.ferzerkerx.demo.joooq.db.Keys;
import com.ferzerkerx.demo.joooq.db.Public;
import com.ferzerkerx.demo.joooq.db.tables.records.AlbumRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Album extends TableImpl<AlbumRecord> {

    private static final long serialVersionUID = 518646828;

    /**
     * The reference instance of <code>PUBLIC.ALBUM</code>
     */
    public static final Album ALBUM = new Album();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AlbumRecord> getRecordType() {
        return AlbumRecord.class;
    }

    /**
     * The column <code>PUBLIC.ALBUM.ALBUM_ID</code>.
     */
    public final TableField<AlbumRecord, Integer> ALBUM_ID = createField("ALBUM_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>PUBLIC.ALBUM.ARTIST_ID</code>.
     */
    public final TableField<AlbumRecord, Integer> ARTIST_ID = createField("ARTIST_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.ALBUM.TITLE</code>.
     */
    public final TableField<AlbumRecord, String> TITLE = createField("TITLE", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>PUBLIC.ALBUM.YEAR</code>.
     */
    public final TableField<AlbumRecord, String> YEAR = createField("YEAR", org.jooq.impl.SQLDataType.VARCHAR(4).nullable(false), this, "");

    /**
     * Create a <code>PUBLIC.ALBUM</code> table reference
     */
    public Album() {
        this(DSL.name("ALBUM"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.ALBUM</code> table reference
     */
    public Album(String alias) {
        this(DSL.name(alias), ALBUM);
    }

    /**
     * Create an aliased <code>PUBLIC.ALBUM</code> table reference
     */
    public Album(Name alias) {
        this(alias, ALBUM);
    }

    private Album(Name alias, Table<AlbumRecord> aliased) {
        this(alias, aliased, null);
    }

    private Album(Name alias, Table<AlbumRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Album(Table<O> child, ForeignKey<O, AlbumRecord> key) {
        super(child, key, ALBUM);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_3, Indexes.RECORD_ARTIST_INDEX_3);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AlbumRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ALBUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AlbumRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AlbumRecord>> getKeys() {
        return Arrays.<UniqueKey<AlbumRecord>>asList(Keys.CONSTRAINT_3);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<AlbumRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<AlbumRecord, ?>>asList(Keys.RECORD_ARTIST);
    }

    public Artist artist() {
        return new Artist(this, Keys.RECORD_ARTIST);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Album as(String alias) {
        return new Album(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Album as(Name alias) {
        return new Album(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Album rename(String name) {
        return new Album(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Album rename(Name name) {
        return new Album(name, null);
    }
}
