/*
 * This file is generated by jOOQ.
 */
package com.ferzerkerx.demo.joooq.db;


import com.ferzerkerx.demo.joooq.db.tables.Album;
import com.ferzerkerx.demo.joooq.db.tables.Artist;
import com.ferzerkerx.demo.joooq.db.tables.records.AlbumRecord;
import com.ferzerkerx.demo.joooq.db.tables.records.ArtistRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AlbumRecord, Integer> IDENTITY_ALBUM = Identities0.IDENTITY_ALBUM;
    public static final Identity<ArtistRecord, Integer> IDENTITY_ARTIST = Identities0.IDENTITY_ARTIST;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AlbumRecord> CONSTRAINT_3 = UniqueKeys0.CONSTRAINT_3;
    public static final UniqueKey<ArtistRecord> CONSTRAINT_7 = UniqueKeys0.CONSTRAINT_7;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AlbumRecord, ArtistRecord> RECORD_ARTIST = ForeignKeys0.RECORD_ARTIST;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AlbumRecord, Integer> IDENTITY_ALBUM = Internal.createIdentity(Album.ALBUM, Album.ALBUM.ALBUM_ID);
        public static Identity<ArtistRecord, Integer> IDENTITY_ARTIST = Internal.createIdentity(Artist.ARTIST, Artist.ARTIST.ARTIST_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AlbumRecord> CONSTRAINT_3 = Internal.createUniqueKey(Album.ALBUM, "CONSTRAINT_3", Album.ALBUM.ALBUM_ID);
        public static final UniqueKey<ArtistRecord> CONSTRAINT_7 = Internal.createUniqueKey(Artist.ARTIST, "CONSTRAINT_7", Artist.ARTIST.ARTIST_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<AlbumRecord, ArtistRecord> RECORD_ARTIST = Internal.createForeignKey(com.ferzerkerx.demo.joooq.db.Keys.CONSTRAINT_7, Album.ALBUM, "RECORD_ARTIST", Album.ALBUM.ARTIST_ID);
    }
}
