/*
 * This file is generated by jOOQ.
 */
package com.ferzerkerx.demo.joooq.db;


import com.ferzerkerx.demo.joooq.db.tables.Album;
import com.ferzerkerx.demo.joooq.db.tables.Artist;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1022534335;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.ALBUM</code>.
     */
    public final Album ALBUM = com.ferzerkerx.demo.joooq.db.tables.Album.ALBUM;

    /**
     * The table <code>PUBLIC.ARTIST</code>.
     */
    public final Artist ARTIST = com.ferzerkerx.demo.joooq.db.tables.Artist.ARTIST;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ALBUM_ALBUM_ID_SEQ,
            Sequences.ARTIST_ARTIST_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Album.ALBUM,
            Artist.ARTIST);
    }
}
