/*
 * This file is generated by jOOQ.
*/
package com.ferzerkerx.demo.joooq.db;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.ALBUM_ALBUM_ID_SEQ</code>
     */
    public static final Sequence<Long> ALBUM_ALBUM_ID_SEQ = new SequenceImpl<Long>("ALBUM_ALBUM_ID_SEQ", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PUBLIC.ARTIST_ARTIST_ID_SEQ</code>
     */
    public static final Sequence<Long> ARTIST_ARTIST_ID_SEQ = new SequenceImpl<Long>("ARTIST_ARTIST_ID_SEQ", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_449610AB_54FF_49A9_A1AE_EB4F60D8ABDA</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_449610AB_54FF_49A9_A1AE_EB4F60D8ABDA = new SequenceImpl<Long>("SYSTEM_SEQUENCE_449610AB_54FF_49A9_A1AE_EB4F60D8ABDA", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_CC796D0C_6A22_40DF_A518_8FFFA0B20A4D</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_CC796D0C_6A22_40DF_A518_8FFFA0B20A4D = new SequenceImpl<Long>("SYSTEM_SEQUENCE_CC796D0C_6A22_40DF_A518_8FFFA0B20A4D", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
