/*
 * This file is generated by jOOQ.
*/
package com.ferzerkerx.demo.joooq.db;


import com.ferzerkerx.demo.joooq.db.tables.Album;
import com.ferzerkerx.demo.joooq.db.tables.Artist;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.ALBUM</code>.
     */
    public static final Album ALBUM = com.ferzerkerx.demo.joooq.db.tables.Album.ALBUM;

    /**
     * The table <code>PUBLIC.ARTIST</code>.
     */
    public static final Artist ARTIST = com.ferzerkerx.demo.joooq.db.tables.Artist.ARTIST;
}
